### ISSUE TITLE
password handling

### ISSUE THREAD

**Issue by torstenwerner** [aimtiaz11/oracle-jdbc-tester#2]
Hi, nice tool. Could you mask the password in the output, please? It would be even greater, if the tool asks for the password without showing it – instead of having the password as a command line argument.

**Comment by aimtiaz11** [comment]
Hi @torstenwerner , one approach would be to use `read` command in linux to store DB username and password into a variable and then using it as normal.

```sh
read DBUSER
read DBPASS
```

```sh
java -jar target/jdbc-tester-1.0.jar $DBUSER $DBPASS jdbc:oracle:thin:@//<host>:<port>/<SID>
```

Maybe I'll update the readme.md about this. 

Making the tool ask for password might make it less usable. Eg. someone wants to run automate JDBC connectivity testing as part of some health check monitoring.
